[mapper]
Sequence = "Sequence"
"Raw file" = "Raw file"
Proteins = "Proteins"
"Modified sequence" = "Modified sequence"
Charge = "Charge"

[modifications_parser]
parse_column = "Modified sequence"
before_aa = false
isalpha = true
isupper = true
pattern = "\\([^()]*\\)|\\([^()]*\\([^()]*\\)[^()]*\\)"

[general]
contaminant_flag = "Cont_"
decoy_flag = true

[modifications_parser.modification_dict]
"(ox)" = "Oxidation"
"(ac)" = "Acetyl"
"(oxidation (m))" = "Oxidation"
"(acetyl (protein n-term))" = "Acetyl"
