[mapper]
sequence_naked = "Sequence"
shortname = "Raw file"
protein = "Proteins"
sequence = "Modified sequence"
charge = "Charge"
decoy = "Reverse"
ms1_int_sum_apex_dn = "Intensity"

[modifications_parser]
parse_column = "Modified sequence"
before_aa = true
isalpha = true
isupper = true
pattern = "([a-z]+)"

[general]
contaminant_flag = "Cont_"
decoy_flag = true

[modifications_parser.modification_dict]
ox = "Oxidation"
c = "Carbamidomethyl"
a = "Acetyl"
decoy = ""

[upload_info]
"datapoint_file" = "*.csv"
"datapoint_file_description" = "Upload the AlphaPept results CSV file (e.g., `alphapept.csv`).\nIt should contain the column 'ms1_int_sum_apex_dn'"
"params_file" = "results.yaml"
"params_file_description" = "Upload the AlphaPept results YAML file (e.g., `alphapept.yaml`)."
