[mapper]
ProteinName = "Proteins"
Sequence = "Sequence"
PrecursorCharge = "Charge"
Reference = "Raw file"
PeptideSequence = "Modified sequence"

[general]
contaminant_flag = "Cont_"
decoy_flag = false

[upload_info]
"datapoint_file" = "*.csv"
"datapoint_file_description" = "Upload the quantms MSstats output CSV file (e.g., `sdrf_openms_design_msstats_in.csv`)."
"params_file" = "*.json"
"params_file_description" = "Upload the quantms pipeline parameter JSON file."
