[mapper]
"proteins" = "Proteins" # this will be the combination of samesets_accessions and subset_accessions after import. Specific to ProlineStudio and MSAngel.
"sequence" = "Sequence"
"modifications" = "Modifications"
"master_quant_peptide_ion_charge" = "Charge"


[condition_mapper]
"abundance_LFQ_Astral_DDA_15min_50ng_Condition_A_REP1" = "A"
"abundance_LFQ_Astral_DDA_15min_50ng_Condition_A_REP2" = "A"
"abundance_LFQ_Astral_DDA_15min_50ng_Condition_A_REP3" = "A"
"abundance_LFQ_Astral_DDA_15min_50ng_Condition_B_REP1" = "B"
"abundance_LFQ_Astral_DDA_15min_50ng_Condition_B_REP2" = "B"
"abundance_LFQ_Astral_DDA_15min_50ng_Condition_B_REP3" = "B"

[run_mapper]
"abundance_LFQ_Astral_DDA_15min_50ng_Condition_A_REP1" = "Condition_A_Sample_Alpha_01"
"abundance_LFQ_Astral_DDA_15min_50ng_Condition_A_REP2" = "Condition_A_Sample_Alpha_02"
"abundance_LFQ_Astral_DDA_15min_50ng_Condition_A_REP3" = "Condition_A_Sample_Alpha_03"
"abundance_LFQ_Astral_DDA_15min_50ng_Condition_B_REP1" = "Condition_B_Sample_Alpha_01"
"abundance_LFQ_Astral_DDA_15min_50ng_Condition_B_REP2" = "Condition_B_Sample_Alpha_02"
"abundance_LFQ_Astral_DDA_15min_50ng_Condition_B_REP3" = "Condition_B_Sample_Alpha_03"

[species_mapper]
"_YEAST" = "YEAST"
"_ECOLI" = "ECOLI"
"_HUMAN" = "HUMAN"

[general]
"contaminant_flag" = "Cont_"
"decoy_flag" = true
