[mapper]
"proteins" = "Proteins" # this will be the combination of samesets_accessions and subset_accessions after import. Specific to ProlineStudio and MSAngel.
"sequence" = "Sequence"
"modifications" = "Modifications"
"master_quant_peptide_ion_charge" = "Charge"

[general]
"contaminant_flag" = "Cont_"
"decoy_flag" = true
"run_name_cleanup" = "^abundance_|\\.mgf$"
