[mapper]
"proteins" = "Proteins" # this will be the combination of samesets_accessions and subset_accessions after import. Specific to ProlineStudio and MSAngel.
"sequence" = "Sequence"
"modifications" = "Modifications"
"master_quant_peptide_ion_charge" = "Charge"

[general]
"contaminant_flag" = "Cont_"
"decoy_flag" = true
"run_name_cleanup" = "^abundance_"

[upload_info]
"datapoint_file" = "*.xlsx"
"datapoint_file_description" = "Upload the MSAngel export Excel file (`.xlsx`) containing the 'Quantified peptide ions' sheet."
"params_file" = "*.json"
"params_file_description" = "Upload the MSAngel pipeline export JSON file."
