[mapper]
Sequence = "Sequence"
"Raw file" = "Raw file"
Proteins = "Proteins"
"Modified sequence" = "Modified sequence"
Charge = "Charge"

[modifications_parser]
parse_column = "Modified sequence"
before_aa = false
isalpha = true
isupper = true
pattern = "\\([^()]*\\)|\\([^()]*\\([^()]*\\)[^()]*\\)"

[general]
contaminant_flag = "Cont_"
decoy_flag = true

[modifications_parser.modification_dict]
"(ox)" = "Oxidation"
"(ac)" = "Acetyl"
"(oxidation (m))" = "Oxidation"
"(acetyl (protein n-term))" = "Acetyl"

[upload_info]
"datapoint_file" = "evidence.txt"
"datapoint_file_description" = "Upload the MaxQuant DIA `evidence.txt` file from the txt output folder."
"params_file" = "mqpar.xml"
"params_file_description" = "Upload the MaxQuant parameter file `mqpar.xml` from the search output folder."
