[mapper]
"FG.LabeledSequence" = "Sequence"
"R.FileName" = "Raw file"
"FG.Charge" = "Charge"
"EG.TotalQuantity (Settings)" = "Intensity"
"PG.ProteinGroups" = "Proteins"

[modifications_parser]
parse_column = "Sequence"
before_aa = false
isalpha = true
isupper = true
pattern = "\\[(.*?)\\]"

[general]
contaminant_flag = "Cont_"
decoy_flag = true

[modifications_parser.modification_dict]
"[oxidation (m)]" = "Oxidation"
"[acetyl (protein n-term)]" = "Acetyl"
"[carbamidomethyl (c)]" = "Carbamidomethyl"
