[mapper]
"sequence_naked" = "Sequence"
"shortname" = "Raw file"
"protein" = "Proteins"
"sequence" = "Modified sequence"
"charge" = "Charge"
"decoy" = "Reverse"
"ms1_int_sum_apex_dn" = "Intensity"

[condition_mapper]
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_01" = "A"
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_02" = "A"
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_03" = "A"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_01" = "B"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_02" = "B"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_03" = "B"

[run_mapper]
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_01" = "Condition_A_Sample_Alpha_01"
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_02" = "Condition_A_Sample_Alpha_02"
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_03" = "Condition_A_Sample_Alpha_03"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_01" = "Condition_B_Sample_Alpha_01"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_02" = "Condition_B_Sample_Alpha_02"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_03" = "Condition_B_Sample_Alpha_03"

[species_mapper]
"_YEAST" = "YEAST"
"_ECOLI" = "ECOLI"
"_HUMAN" = "HUMAN"

[modifications_parser]
"parse_column" = "Modified sequence"
"before_aa" = true
"isalpha" = true
"isupper" = true
"pattern"="([a-z]+)"
"modification_dict" = {"ox" = "Oxidation", "c" = "Carbamidomethyl", "a" = "Acetyl", "decoy" = ""}

[general]
"contaminant_flag" = "Cont_"
"decoy_flag" = true
