[mapper]
"ProteinName" = "Proteins"
"Sequence" = "Sequence"
"PrecursorCharge" = "Charge"
"Reference" = "Raw file"
"PeptideSequence" = "Modified sequence"

[condition_mapper]
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_01.mzML" = "A"
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_02.mzML" = "A"
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_03.mzML" = "A"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_01.mzML" = "B"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_02.mzML" = "B"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_03.mzML" = "B"

[run_mapper]
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_01.mzML" = "Condition_A_Sample_Alpha_01"
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_02.mzML" = "Condition_A_Sample_Alpha_02"
"LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_03.mzML" = "Condition_A_Sample_Alpha_03"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_01.mzML" = "Condition_B_Sample_Alpha_01"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_02.mzML" = "Condition_B_Sample_Alpha_02"
"LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_03.mzML" = "Condition_B_Sample_Alpha_03"


[species_mapper]
"_YEAST" = "YEAST"
"_ECOLI" = "ECOLI"
"_HUMAN" = "HUMAN"


[general]
"contaminant_flag" = "Cont_"
"decoy_flag" = false
