[mapper]
"Base Sequence" = "Sequence"
"File Name" = "Raw file"
"Full Sequence" = "Modified sequence"
"Precursor Charge" = "Charge"
"Peak intensity" = "Intensity"

[modifications_parser]
parse_column = "Modified sequence"
before_aa = false
isalpha = true
isupper = true
pattern = "\\[(.*?)\\]"

[general]
contaminant_flag = "Cont_"
decoy_flag = true

[modifications_parser.modification_dict]
"[common fixed:carbamidomethyl on c]" = "Carbamidomethyl"
"[common variable:oxidation on m]" = "Oxidation"
"[common biological:acetylation on x]" = "Acetyl"
