[mapper]
ProteinName = "Proteins"
Sequence = "Sequence"
PrecursorCharge = "Charge"
Reference = "Raw file"
PeptideSequence = "Modified sequence"

[general]
contaminant_flag = "Cont_"
decoy_flag = false
