[mapper]
sequence_naked = "Sequence"
shortname = "Raw file"
protein = "Proteins"
sequence = "Modified sequence"
charge = "Charge"
decoy = "Reverse"
ms1_int_sum_apex_dn = "Intensity"

[modifications_parser]
parse_column = "Modified sequence"
before_aa = true
isalpha = true
isupper = true
pattern = "([a-z]+)"

[general]
contaminant_flag = "Cont_"
decoy_flag = true

[modifications_parser.modification_dict]
ox = "Oxidation"
c = "Carbamidomethyl"
a = "Acetyl"
decoy = ""
