[mapper]
sequence = "Sequence"
rawfile = "Raw file"
proteins = "Proteins"
ProForma = "Modified sequence"
charge = "Charge"
area = "Intensity"

[general]
contaminant_flag = "Cont_"
decoy_flag = true

[modifications_parser]
parse_column = "proforma"
before_aa = false
isalpha = true
isupper = true
pattern = "(?<=\\[).+?(?=\\])"

[modifications_parser.modification_dict]
"mod:00397" = "Carbamidomethyl"
"mod:01160" = "Ammonia-loss"
"mod:00394" = "Acetyl"
"mod:00425" = "Oxidation"
"mod:00704" = "Dehydrated"
"mod:00719" = "Oxidation"
