[theme]
base="light"
primaryColor="#007A78"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#EEF2F7"
textColor="#1B2A4A"

[global]
disableWidgetStateDuplicationWarning = true

[server]
maxUploadSize = 1000

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false