[mapper]
"spectra_ref" = "spectrum_id"
"sequence" = "sequence"
"search_engine_score[1]" = "score"
"opt_ms_run[1]_aa_scores" = "aa_scores"

[spectrum_id_mapper]
"pattern" = "index=(\\d+)"

[modifications_parser]
"parse_column" = "sequence"
"before_aa" = false
"isalpha" = true
"isupper" = true
"pattern" = "([\\d+-.]+)"
"modification_dict" = {"+57.021" = "UNIMOD:4", "+15.995" = "UNIMOD:15", "+0.984" = "UNIMOD:7", "+42.011" = "UNIMOD:1", "+43.006" = "UNIMOD:5", "-17.027" = "UNIMOD:385"}