[mapper]
"spectra_ref" = "spectrum_id"
"sequence" = "sequence"
"search_engine_score[1]" = "score"
"opt_ms_run[1]_aa_scores" = "aa_scores"

[spectrum_id_mapper]
"pattern" = "index=(\\d+)"

[sequence_mapper]

[modifications_parser]
"parse_column" = "sequence"
"before_aa" = false
"isalpha" = true
"isupper" = true
"pattern" = "\\(([^)]+)\\)"
"modification_dict" = {"(+57.02)" = "UNIMOD:4", "(+15.99)" = "UNIMOD:35", "(+.98)" = "UNIMOD:7", "(+42.01)" = "UNIMOD:1", "(+43.00)" = "UNIMOD:5", "(-17.02)" = "UNIMOD:385", "+43.006-17.027" = "Formula:H-2C1O1"}
