[quant_lfq_DDA_ion_QExactive]
"AlphaPept" = "parse_settings_alphapept.toml"
"FragPipe" = "parse_settings_fragpipe.toml"
"i2MassChroQ" = "parse_settings_i2massChroQ.toml"
"MaxQuant" = "parse_settings_maxquant.toml"
"MSAngel" = "parse_settings_msangel.toml"
"PEAKS" = "parse_settings_peaks.toml"
"ProlineStudio" = "parse_settings_proline.toml"
"quantms" = "parse_settings_msstats.toml"
"Sage" = "parse_settings_sage.toml"
"WOMBAT" = "parse_settings_wombat.toml"
"Custom" = "parse_settings_custom.toml"

[quant_lfq_DDA_peptidoform]
"WOMBAT" = "parse_settings_wombat.toml"
"PEAKS" = "parse_settings_peaks.toml"
"Proteome Discoverer" = "parse_settings_proteomediscoverer.toml"
"Custom" = "parse_settings_custom.toml"

[quant_lfq_DIA_ion_AIF]
"DIA-NN" = "parse_settings_diann.toml"
"MaxQuant" = "parse_settings_maxdia.toml"
"FragPipe (DIA-NN quant)" = "parse_settings_diann.toml"
"FragPipe" = "parse_settings_fragpipe_DIA.toml"
"Spectronaut" = "parse_settings_spectronaut.toml"
"AlphaDIA" = "parse_settings_alphadia.toml"
"MSAID" = "parse_settings_msaid.toml"
"PEAKS" = "parse_settings_peaks.toml"
"Custom" = "parse_settings_custom.toml"

[quant_lfq_DIA_ion_diaPASEF]
"DIA-NN" = "parse_settings_diann.toml"
"MaxQuant" = "parse_settings_maxdia.toml"
"FragPipe (DIA-NN quant)" = "parse_settings_diann.toml"
"FragPipe" = "parse_settings_fragpipe_DIA.toml"
"Spectronaut" = "parse_settings_spectronaut.toml"
"AlphaDIA" = "parse_settings_alphadia.toml"
"MSAID" = "parse_settings_msaid.toml"
"Custom" = "parse_settings_custom.toml"
"PEAKS" = "parse_settings_peaks.toml"

[quant_lfq_DIA_ion_singlecell]
"DIA-NN" = "parse_settings_diann.toml"
"MaxQuant" = "parse_settings_maxdia.toml"
"FragPipe (DIA-NN quant)" = "parse_settings_diann.toml"
"FragPipe" = "parse_settings_fragpipe_DIA.toml"
"Spectronaut" = "parse_settings_spectronaut.toml"
"AlphaDIA" = "parse_settings_alphadia.toml"
"MSAID" = "parse_settings_msaid.toml"
"Custom" = "parse_settings_custom.toml"
"Sage" = "parse_settings_sage.toml"

[quant_lfq_DIA_ion_Astral]
"DIA-NN" = "parse_settings_diann.toml"
"MaxQuant" = "parse_settings_maxdia.toml"
"FragPipe (DIA-NN quant)" = "parse_settings_diann.toml"
"FragPipe" = "parse_settings_fragpipe_DIA.toml"
"Spectronaut" = "parse_settings_spectronaut.toml"
"AlphaDIA" = "parse_settings_alphadia.toml"
"MSAID" = "parse_settings_msaid.toml"
"Custom" = "parse_settings_custom.toml"
"PEAKS" = "parse_settings_peaks.toml"

[quant_lfq_DDA_ion_Astral]
"AlphaPept" = "parse_settings_alphapept.toml"
"FragPipe" = "parse_settings_fragpipe.toml"
"i2MassChroQ" = "parse_settings_i2massChroQ.toml"
"MaxQuant" = "parse_settings_maxquant.toml"
"MSAngel" = "parse_settings_msangel.toml"
"PEAKS" = "parse_settings_peaks.toml"
"ProlineStudio" = "parse_settings_proline.toml"
"quantms" = "parse_settings_msstats.toml"
"Sage" = "parse_settings_sage.toml"
"WOMBAT" = "parse_settings_wombat.toml"
"Custom" = "parse_settings_custom.toml"