[mapper]
"Sequence" = "Sequence"
"Raw file" = "Raw file"
"Proteins" = "Proteins"
"Modified sequence" = "Modified sequence"
"Charge" = "Charge"

[condition_mapper]
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEA_QC_B13_2uL" = "A"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEA_QC_B14_2uL" = "A"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEA_QC_B15_2uL" = "A"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEA_QC_B17_2uL" = "A"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEA_QC_B18_2uL" = "A"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEA_QC_B20_2uL" = "A"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEB_QC_O2_2uL" = "B"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEB_QC_O3_2uL" = "B"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEB_QC_O5_2uL" = "B"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEB_QC_O6_2uL" = "B"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEB_QC_O7_2uL" = "B"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEB_QC_O8_2uL" = "B"

[run_mapper]
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEA_QC_B13_2uL" = "HYEA_QC_B13"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEA_QC_B14_2uL" = "HYEA_QC_B14"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEA_QC_B15_2uL" = "HYEA_QC_B15"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEA_QC_B17_2uL" = "HYEA_QC_B17"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEA_QC_B18_2uL" = "HYEA_QC_B18"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEA_QC_B20_2uL" = "HYEA_QC_B20"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEB_QC_O2_2uL" = "HYEB_QC_O2"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEB_QC_O3_2uL" = "HYEB_QC_O3"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEB_QC_O5_2uL" = "HYEB_QC_O5"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEB_QC_O6_2uL" = "HYEB_QC_O6"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEB_QC_O7_2uL" = "HYEB_QC_O7"
"20251014_LSMBO_CC_Astral_IO08_140SPD_HYEB_QC_O8_2uL" = "HYEB_QC_O8"

[species_mapper]
"_YEAST" = "YEAST"
"_ECOLI" = "ECOLI"
"_HUMAN" = "HUMAN"

[modifications_parser]
"parse_column" = "Modified sequence"
"before_aa" = false
"isalpha" = true
"isupper" = true
"pattern" = "\\([^()]*\\)|\\([^()]*\\([^()]*\\)[^()]*\\)"
"modification_dict" = {"(ox)" = "Oxidation", "(ac)" = "Acetyl", "(oxidation (m))" = "Oxidation", "(acetyl (protein n-term))" = "Acetyl"}

[general]
"contaminant_flag" = "Cont_"
"decoy_flag" = true

[upload_info]
"datapoint_file" = "evidence.txt"
"datapoint_file_description" = "Upload the MaxQuant DIA `evidence.txt` file from the txt output folder."
"params_file" = "mqpar.xml"
"params_file_description" = "Upload the MaxQuant parameter file `mqpar.xml` from the search output folder."
