[species_expected_ratio]
[species_expected_ratio.YEAST]
"A_vs_B" = 2.0
"color" = "#88ccef"

[species_expected_ratio.ECOLI]
"A_vs_B" = 0.25
"color" = "#cc6777"

[species_expected_ratio.HUMAN]
"A_vs_B" = 1.0
"color" = "#ddcc77"

[species_mapper]
"_YEAST" = "YEAST"
"_ECOLI" = "ECOLI"
"_HUMAN" = "HUMAN"

[general]
"min_count_multispec" = 1
"level" = "peptidoform"

[[samples]]
raw_file = "abundance_A_1"
sample_name = "Condition_A_Sample_Alpha_01"
condition = "A"

[[samples]]
raw_file = "abundance_A_2"
sample_name = "Condition_A_Sample_Alpha_02"
condition = "A"

[[samples]]
raw_file = "abundance_A_3"
sample_name = "Condition_A_Sample_Alpha_03"
condition = "A"

[[samples]]
raw_file = "abundance_B_1"
sample_name = "Condition_B_Sample_Alpha_01"
condition = "B"

[[samples]]
raw_file = "abundance_B_2"
sample_name = "Condition_B_Sample_Alpha_02"
condition = "B"

[[samples]]
raw_file = "abundance_B_3"
sample_name = "Condition_B_Sample_Alpha_03"
condition = "B"

