[mapper]
"Protein Accessions" = "Proteins"
"Sequence" = "sequence"
"Modifications" = "modifications"

[run_mapper]
"Abundances (Normalized): F1: Sample, ConditionA" = "Condition_A_Sample_Alpha_01"
"Abundances (Normalized): F2: Sample, ConditionA" = "Condition_A_Sample_Alpha_02"
"Abundances (Normalized): F3: Sample, ConditionA" = "Condition_A_Sample_Alpha_03"
"Abundances (Normalized): F4: Sample, ConditionB" = "Condition_B_Sample_Alpha_01"
"Abundances (Normalized): F5: Sample, ConditionB" = "Condition_B_Sample_Alpha_02"
"Abundances (Normalized): F6: Sample, ConditionB" = "Condition_B_Sample_Alpha_03"

[general]
"contaminant_flag" = "Cont_"
"decoy_flag" = true
