"""
Generate the module grid RST snippet for the ProteoBench documentation homepage.

Usage
-----
    cd <repo-root>
    python docs/generate_module_grid.py

The script writes ``docs/module_grid_generated.rst``.  Commit that file; CI
will re-run the script and fail if the committed version is stale.

Design
------
* Reads module metadata by **AST-parsing** the Variables dataclasses in
  ``webinterface/pages/pages_variables/`` — no imports, no Streamlit dependency.
* Reads ``docs/module_in_discussion_grid_extra.yaml`` for modules that are only
  discussed on GitHub (no Variables dataclass yet).
* Outputs a sphinx-design grid of cards for implemented modules followed by a
  bullet list of discussion-only modules.
"""

import ast
import sys
from pathlib import Path

import yaml

# ---------------------------------------------------------------------------
# Paths (all relative to the repository root, which we derive from this file)
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
PAGES_VARIABLES_DIR = REPO_ROOT / "webinterface" / "pages" / "pages_variables"
EXTRA_YAML = REPO_ROOT / "docs" / "module_in_discussion_grid_extra.yaml"
OUTPUT_RST = REPO_ROOT / "docs" / "module_grid_generated.rst"

APP_BASE_URL = "https://proteobench.cubimed.rub.de"

# ---------------------------------------------------------------------------
# AST helpers
# ---------------------------------------------------------------------------

_SENTINEL = object()


def _ast_extract_defaults(filepath: Path) -> dict:
    """Return a dict of {field_name: default_value} for the first dataclass found.

    Only handles simple string and bool literal defaults.  Multi-line string
    concatenations are not needed here.
    """
    source = filepath.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(filepath))

    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        # Check that the class is decorated with @dataclass
        has_dataclass = any(
            (isinstance(d, ast.Name) and d.id == "dataclass")
            or (isinstance(d, ast.Attribute) and d.attr == "dataclass")
            for d in node.decorator_list
        )
        if not has_dataclass:
            continue

        defaults: dict = {}
        for item in ast.walk(node):
            if not isinstance(item, ast.AnnAssign):
                continue
            if not isinstance(item.target, ast.Name):
                continue
            name = item.target.id
            if item.value is None:
                continue
            value = item.value
            # Simple string constant
            if isinstance(value, ast.Constant) and isinstance(value.value, (str, bool)):
                defaults[name] = value.value
            # Boolean Name node (True / False written without quotes — handled above
            # as ast.Constant in Python ≥ 3.8, but kept for safety)
            elif isinstance(value, ast.Name) and value.id in ("True", "False"):
                defaults[name] = value.id == "True"
        return defaults

    return {}


# ---------------------------------------------------------------------------
# Badge mapping
# ---------------------------------------------------------------------------


def _release_stage(defaults: dict) -> tuple[str, str]:
    """Return (badge_role, badge_label) from warning flags."""
    if defaults.get("archived_warning", False):
        return "bdg-dark", "archived"
    if defaults.get("alpha_warning", False):
        return "bdg-info", "in development"
    return "bdg-success", "active"


# ---------------------------------------------------------------------------
# RST generation helpers
# ---------------------------------------------------------------------------

CARD_COLUMNS = "6 6 4 4"

_HEADER = """\
.. DO NOT EDIT — auto-generated by ``docs/generate_module_grid.py``.
.. Re-run the script whenever a Variables dataclass is added or changed.

"""

_SECTION_HEADER = """\
Available ProteoBench modules
==============================

.. For card colors, use:
.. in development: info
.. active: success
.. archived: dark

"""


def _card_rst(label: str, description: str, badge_role: str, badge_label: str, app_url: str, doc_url: str) -> str:
    """Return the RST block for a single sphinx-design card."""
    lines = [
        f"    .. grid-item-card:: {label}",
        f"        :columns: {CARD_COLUMNS}",
        "        :padding: 1",
        "",
        f"        :{badge_role}:`{badge_label}`",
        "        ^^^",
        f"        {description}",
        "        +++",
        f"        `Web app <{app_url}>`__ · `Documentation <{doc_url}>`__",
        "",
        "",
    ]
    return "\n".join(lines)


def _discussion_list_rst(modules: list[dict]) -> str:
    """Return an RST bullet list for discussion-only modules."""
    if not modules:
        return ""
    lines = [
        "",
        "Modules in discussion",
        "----------------------",
        "",
    ]
    for mod in modules:
        url = mod["url"]
        label = mod["label"]
        desc = mod.get("description", "")
        entry = f"* `{label} <{url}>`__"
        if desc:
            entry += f" — {desc}"
        lines.append(entry)
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    # 1. Collect module metadata from Variables dataclasses
    variable_files = sorted(PAGES_VARIABLES_DIR.rglob("*_variables.py"))

    modules: list[dict] = []
    for vf in variable_files:
        if vf.name.startswith("_"):
            continue
        defaults = _ast_extract_defaults(vf)
        if "sidebar_label" not in defaults:
            print(f"  skip {vf.name}: no sidebar_label found", file=sys.stderr)
            continue
        badge_role, badge_label = _release_stage(defaults)
        modules.append(
            {
                "label": defaults["sidebar_label"],
                "description": defaults.get("documentation_description", ""),
                "app_url": APP_BASE_URL + defaults.get("sidebar_path", ""),
                "doc_url": defaults.get("doc_url", ""),
                "badge_role": badge_role,
                "badge_label": badge_label,
                "category": defaults.get("sidebar_category", ""),
            }
        )

    if not modules:
        print("ERROR: No modules found — check PAGES_VARIABLES_DIR path.", file=sys.stderr)
        sys.exit(1)

    # Sort: active first (alphabetically within each group), then archived
    def _sort_key(m: dict) -> tuple:
        order = {"active": 0, "in development": 1, "archived": 2}
        return (order.get(m["badge_label"], 9), m["label"].lower())

    modules.sort(key=_sort_key)

    # 2. Load discussion-only modules from YAML
    discussion_modules: list[dict] = []
    if EXTRA_YAML.exists():
        with EXTRA_YAML.open(encoding="utf-8") as fh:
            extra = yaml.safe_load(fh)
        discussion_modules = extra.get("modules", [])
    else:
        print(f"  WARNING: {EXTRA_YAML} not found; skipping discussion modules.", file=sys.stderr)

    # 3. Build RST
    parts = [_HEADER, _SECTION_HEADER, ".. grid::\n\n"]
    for mod in modules:
        parts.append(
            _card_rst(
                label=mod["label"],
                description=mod["description"],
                badge_role=mod["badge_role"],
                badge_label=mod["badge_label"],
                app_url=mod["app_url"],
                doc_url=mod["doc_url"],
            )
        )
    parts.append("\n")

    # Button linking to the full module descriptions page
    parts.append(
        ".. button-ref:: available-modules/index\n"
        "    :ref-type: doc\n"
        "    :class: sd-px-4\n"
        "    :color: primary\n"
        "\n"
        "    Module descriptions\n"
    )

    parts.append(_discussion_list_rst(discussion_modules))

    rst_content = "".join(parts)

    # 4. Write output
    OUTPUT_RST.write_text(rst_content, encoding="utf-8")
    print(f"Written: {OUTPUT_RST.relative_to(REPO_ROOT)}")
    print(f"  {len(modules)} implemented module(s), {len(discussion_modules)} discussion module(s)")


if __name__ == "__main__":
    main()
