[mapper]
"Modified.Sequence" = "Sequence"
"Run" = "Raw file"
"Protein.Ids" = "Proteins"
"Precursor.Charge" = "Charge"
"Precursor.Normalised" = "Intensity"

[condition_mapper]
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_240pg_10pg_H_Y_r1" = "A"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_240pg_10pg_H_Y_r2" = "A"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_240pg_10pg_H_Y_r3" = "A"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_200pg_50pg_H_Y_r1" = "B"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_200pg_50pg_H_Y_r2" = "B"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_200pg_50pg_H_Y_r3" = "B"

[run_mapper]
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_240pg_10pg_H_Y_r1" = "Condition_A_Sample_1"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_240pg_10pg_H_Y_r2" = "Condition_A_Sample_2"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_240pg_10pg_H_Y_r3" = "Condition_A_Sample_3"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_200pg_50pg_H_Y_r1" = "Condition_B_Sample_1"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_200pg_50pg_H_Y_r2" = "Condition_B_Sample_2"
"20231123_DIA_240k_20Th_40ms_FAIMSCV-48_gas3p8_200pg_50pg_H_Y_r3" = "Condition_B_Sample_3"

[species_mapper]
"_YEAST" = "YEAST"
"_HUMAN" = "HUMAN"

[modifications_parser]
"parse_column" = "Sequence"
"before_aa" = false
"isalpha" = true
"isupper" = true
"pattern" = "\\(([^()]*)\\)"
"modification_dict" = {"(unimod:35)" = "Oxidation", "(unimod:1)" = "Acetyl", "(unimod:4)" = "Carbamidomethyl"}

[general]
"contaminant_flag" = "Cont_"
"decoy_flag" = true

[upload_info]
"datapoint_file" = "report.tsv or report.parquet"
"datapoint_file_description" = "Upload the DIA-NN report file (`report.tsv` or `report.parquet`)."
"params_file" = "report.log.txt"
"params_file_description" = "Upload the DIA-NN log file (`report.log.txt`)."

[upload_info_overrides."FragPipe (DIA-NN quant)"]
"datapoint_file" = "report.tsv or report.parquet"
"datapoint_file_description" = "Upload the DIA-NN report file found in the `dia-quant-output` folder (`report.tsv` or `report.parquet`)."
"params_file" = "fragpipe.workflow"
"params_file_description" = "Upload the FragPipe workflow file (.workflow)."
