[mapper]
"Modified.Sequence" = "Sequence"
Run = "Raw file"
"Protein.Ids" = "Proteins"
"Precursor.Charge" = "Charge"
"Precursor.Normalised" = "Intensity"

[modifications_parser]
parse_column = "Sequence"
before_aa = false
isalpha = true
isupper = true
pattern = "\\(([^()]*)\\)"

[general]
contaminant_flag = "Cont_"
decoy_flag = true

[modifications_parser.modification_dict]
"(unimod:35)" = "Oxidation"
"(unimod:1)" = "Acetyl"
"(unimod:4)" = "Carbamidomethyl"

[upload_info]
"datapoint_file" = "report.tsv or report.parquet"
"datapoint_file_description" = "Upload the DIA-NN report file (`report.tsv` or `report.parquet`)."
"params_file" = "report.log.txt"
"params_file_description" = "Upload the DIA-NN log file (`report.log.txt`)."

[upload_info_overrides."FragPipe (DIA-NN quant)"]
"params_file" = "fragpipe.workflow"
"params_file_description" = "Upload the FragPipe workflow file (.workflow)."
