[mapper]
"Accession" = "Proteins"
"Peptide" = "Sequence"
"z" = "Charge"

[condition_mapper]
"A9_G_DIA_nLC_tTOF_R1 Normalized Area" = "A"
"A9_G_DIA_nLC_tTOF_R2 Normalized Area" = "A"
"A9_G_DIA_nLC_tTOF_R3 Normalized Area" = "A"
"A9_G_DIA_nLC_tTOF_R4 Normalized Area" = "A"
"A9_G_DIA_nLC_tTOF_R5 Normalized Area" = "A"
"A9_G_DIA_nLC_tTOF_R6 Normalized Area" = "A"
"B9_G_DIA_nLC_tTOF_R1 Normalized Area" = "B"
"B9_G_DIA_nLC_tTOF_R2 Normalized Area" = "B"
"B9_G_DIA_nLC_tTOF_R3 Normalized Area" = "B"
"B9_G_DIA_nLC_tTOF_R4 Normalized Area" = "B"
"B9_G_DIA_nLC_tTOF_R5 Normalized Area" = "B"
"B9_G_DIA_nLC_tTOF_R6 Normalized Area" = "B"

[run_mapper]
"A9_G_DIA_nLC_tTOF_R1 Normalized Area" = "Condition_A_Sample_Alpha_01"
"A9_G_DIA_nLC_tTOF_R2 Normalized Area" = "Condition_A_Sample_Alpha_02"
"A9_G_DIA_nLC_tTOF_R3 Normalized Area" = "Condition_A_Sample_Alpha_03"
"A9_G_DIA_nLC_tTOF_R4 Normalized Area" = "Condition_A_Sample_Alpha_04"
"A9_G_DIA_nLC_tTOF_R5 Normalized Area" = "Condition_A_Sample_Alpha_05"
"A9_G_DIA_nLC_tTOF_R6 Normalized Area" = "Condition_A_Sample_Alpha_06"
"B9_G_DIA_nLC_tTOF_R1 Normalized Area" = "Condition_B_Sample_Alpha_01"
"B9_G_DIA_nLC_tTOF_R2 Normalized Area" = "Condition_B_Sample_Alpha_02"
"B9_G_DIA_nLC_tTOF_R3 Normalized Area" = "Condition_B_Sample_Alpha_03"
"B9_G_DIA_nLC_tTOF_R4 Normalized Area" = "Condition_B_Sample_Alpha_04"
"B9_G_DIA_nLC_tTOF_R5 Normalized Area" = "Condition_B_Sample_Alpha_05"
"B9_G_DIA_nLC_tTOF_R6 Normalized Area" = "Condition_B_Sample_Alpha_06"

[modifications_parser]
"parse_column" = "Sequence"
"before_aa" = false
"isalpha" = true
"isupper" = true
"pattern"="(?<=\\().+?(?=\\))"
"modification_dict" = {"+57.02" = "Carbamidomethyl", "+15.99" = "Oxidation", "-17.026548" = "Gln->pyro-Glu", "-18.010565" = "Glu->pyro-Glu", "+42.01" = "Acetyl"}

[general]
"contaminant_flag" = "Cont_"
"decoy_flag" = false
