[mapper]
"Modified.Sequence" = "Sequence"
Run = "Raw file"
"Protein.Names" = "Proteins"
"Precursor.Charge" = "Charge"
"Precursor.Quantity" = "Intensity"

[modifications_parser]
parse_column = "Sequence"
before_aa = false
isalpha = true
isupper = true
pattern = "\\(([^()]*)\\)"

[general]
contaminant_flag = "Cont_"
decoy_flag = true

[modifications_parser.modification_dict]
"(unimod:35)" = "Oxidation"
"(unimod:1)" = "Acetyl"
"(unimod:4)" = "Carbamidomethyl"
