import json
from io import StringIO
import domaps


class Subcellprofile_Scores:
    def __init__(self):
        self.sd: domaps.SpatialDataSet = None

    def generate_SpatialDataSet(
        self,
        content: StringIO,
        settings: dict,
    ) -> None:
        """
        Generate a SpatialDataset object from the content and settings.

        Input for this function should be generated by the io module.
        """
        sd = domaps.SpatialDataSet.from_settings(settings)
        sd.run_pipeline(content=content)
        self.sd = sd

    def create_sd_json(self, filename: str) -> None:
        """
        Create the JSON download file for the analysed datasets.
        """
        json.dump(self.sd.analysed_datasets_dict, filename, indent=4, sort_keys=True)
