"""Basic scoring module for Subcellprofile modules."""

import json
from io import StringIO

import domaps


class Subcellprofile_Scores:
    """
    Scoring module for calculation of metrics from the Subcellular Profiling module.
    """

    def __init__(self):
        """Initialise the Subcellprofile_Scores object."""
        self.sd: domaps.SpatialDataSet = None
        self.sdc: domaps.SpatialDataSetComparison = None

    def generate_SpatialDataSet(
        self,
        content: StringIO,
        settings: dict,
    ) -> None:
        """
        Generate a SpatialDataset object from the content and settings.

        Input for this function should be generated by the io module.

        Parameters
        ----------
        content : StringIO
            The content of the dataset.
        settings : dict
            The settings for the dataset.
        """
        sd = domaps.SpatialDataSet.from_settings(settings)
        sd.run_pipeline(content=content)
        self.sd = sd

    def create_sd_json(self, filename: str) -> None:
        """
        Create the JSON download file for the analysed datasets.

        Parameters
        ----------
        filename : str
            The name of the file to save the JSON to.
        """
        json.dump(self.sd.analysed_datasets_dict, filename, indent=4, sort_keys=True)

    def run_SpatialDataSetComparison(self):
        """
        Generate a SpatialDataSetComparison object from the SpatialDataSet object.
        """
        self.sdc = domaps.SpatialDataSetComparison()
        self.sdc.json_dict = self.sd.analysed_datasets_dict
        self.sdc.read_jsonFile()
        self.sdc.calc_biological_precision()
        self.sdc.calculate_global_scatter(metric="manhattan distance to average profile", consolidation="average")

    def get_metrics(self):
        """
        Return the metrics from the SpatialDataSetComparison object.
        """
        #     depth_id_1: int = 0
        # depth_profile_1: int = 0
        # depth_id_3: int = 0
        # depth_profile_3: int = 0
        # median_profile_reproducibility
        # mean_complex_scatter

    def complex_scatter_unnormalized(self, mode="mean") -> float:
        """
        Return the mean complex scatter from the SpatialDataSetComparison object.

        Parameters
        ----------
        mode : str
            The mode to calculate the complex scatter. Default is 'mean'.

        Returns
        -------
        float
            The mean complex scatter.
        """
        complex_scatter = self.sdc.aggregate_cluster_scatter(
            normalization=None,
            aggregate_proteins=True,
            aggregate_maps=False,
            min_size=5,
        )

        if mode == "mean":
            return complex_scatter.mean()["distance"]
        else:
            raise ValueError(f"Invalid mode {mode}. Please use 'mean'.")
